// <auto-generated />
namespace triluatsoft.tls.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class HNH_Added_Persons_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HNH_Added_Persons_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "202005261733339_HNH_Added_Persons_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
