// <auto-generated />
namespace triluatsoft.tls.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class HNH_Added_StudentsOfClassroom_Table1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HNH_Added_StudentsOfClassroom_Table1));
        
        string IMigrationMetadata.Id
        {
            get { return "202005311455485_HNH_Added_StudentsOfClassroom_Table1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
